### PR TITLE
Shell script and start output optimization

### PR DESCRIPTION
**Pull request by baschny**
* Better output while starting
* Code style reformatting (2 spaces indent etc)

### CODE REVIEW

**Comment by baschny** [comment]
@remuslazar first commit can be reviewed (adds new stuff), second one just reformats the code

**Review by remuslazar — APPROVED** [review]
👍 looks good to me! I did only a code-wise review, though.

**Comment by remuslazar** [comment]
@baschny do u want to also add the composer "no progress" Option, to make the output even nicer?

**Comment by baschny** [comment]
> @baschny do u want to also add the composer "no progress" Option, to make the output even nicer?

Good idea! f80a5ce91499d0a98c90860e85289c6a00c6d679

**Review by remuslazar — APPROVED** [review]
👍

**Pull request merged**
